version: '3.8'

services:
  http:
    image: nginx
    container_name: http
    ports:
      - "8080:80"
    volumes:
      - ./src:/app
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - tp3-network
    depends_on:
      - script

  script:
    build: .
    container_name: script
    volumes:
      - ./src:/app
    networks:
      - tp3-network
    depends_on:
      - data

  data:
    image: mariadb:latest
    container_name: data
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - tp3-network

networks:
  tp3-network:
    driver: bridge
